DROP TABLE customer CASCADE CONSTRAINT;
DROP TABLE rent CASCADE CONSTRAINT;
DROP TABLE rent_return;
DROP TABLE reservation;
DROP TABLE branch CASCADE CONSTRAINT;
DROP TABLE vehicle;
DROP TABLE vehicletype;

COMMIT;